### PR TITLE
Regenerate sigfiles 1.5

### PR DESCRIPTION
**Pull request by junichi11**
There are no parser error and exception in NB 17.

Fix two issues: 5781a88f002411d60dbd3c4f6ba7fb985708669c and 789e8179948cdcc02c09ab2af3ef4d10437c3f20

Add the licenses to README: c4991ed8afb0bbbfb308fa686dd8d3e467e67233

### CODE REVIEW

**Review by tmysik — APPROVED** [review]
@junichi11 Junichi, you really don't need my review and approval 🙂

**Comment by tmysik** [comment]
@junichi11 

Just 2 things:
- the source branch can be deleted but leaving up to you
- any idea how to make PRs easier to review? I mean, how to "ignore" changes in the output files? 🤔 

Thanks!

**Comment by junichi11** [comment]
@tmysik 

> Junichi, you really don't need my review and approval

OK :)

> the source branch

What does this mean? `resources/php-chunked-xhtml`?

> any idea how to make PRs easier to review? I mean, how to "ignore" changes in the output files?

Let's create PRs without output files. I'll push output files directly after I generate them on my environment and verify whether it is OK. (Maybe, It would be better to create them in the same environment.)

Thanks!

**Comment by tmysik** [comment]
The source branch of this PR :) I did not delete it...

**Comment by junichi11** [comment]
Ah, I see. Thank you!

**Pull request merged**
